[window]
decorations = "none"
opacity = 1
startup_mode = "Maximized"
blur = true

[terminal]

[terminal.shell]
program = "/home/vohaha/.config/alacritty/start-tmux.sh"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font, Bold"
italic.family = "JetBrainsMono Nerd Font, Italic"
size = 16
